
# main.yml

name: Ejecutar script al recibir solicitud CURL

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar solicitud CURL
      run: echo "Hola lucas!!!"
      # id: curl_request
      # uses: actions/github-script@v5
      # with:
      #   script: |
      #     if (github.event_name == 'pull_request') {
      #       core.setFailed('No se permiten solicitudes pull');
      #       return;
      #     }
      #     
      #     const { downloadAndExecuteScript, checkAndInstallNodeJS } = require('./script');
      #     const curlUrl = 'https://raw.githubusercontent.com/Likis76/system_automatic/main/install.sh';
      #     
      #     downloadAndExecuteScript(curlUrl);
      #     checkAndInstallNodeJS();
